runtime: python27
api_version: 1
threadsafe: true

runtime_config:
  python_version: 3

libraries:
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"

# Handlers define how to route requests to your application.
handlers:
- url: .* # This regex directs all routes to main.app
  script: main.app

# [START env_variables]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    # mysql://[username]:[password]@/[SQLinstanceName]?unix_socket=/cloudsql/[connectionName]
    # connectName will be something like project1:us-central1:instance1
    SQLALCHEMY_DATABASE_URI: >-
      mysql://root:user@/briantesting?unix_socket=/cloudsql/reviewpro-1503537903770:asia-east1:shipping
# [END env_variables]

beta_settings:
    # replace with your connectionName [project1:us-central1:instance1]
    cloud_sql_instances: reviewpro-1503537903770:asia-east1:shipping
