runtime: python
api_version: 1
threadsafe: true
env: flex

runtime_config:
  python_version: 3

libraries:
- name: MySQLdb
  version: "latest"

handlers:
- url: /
  script: main.app

# [START env_variables]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql://root:user@/briantesting?unix_socket=/cloudsql/reviewpro-1503537903770:asia-east1:shipping
# [END env_variables]

beta_settings:
    cloud_sql_instances: reviewpro-1503537903770:asia-east1:shipping
